### ISSUE TITLE
Does not install properly on macOS Catalina

### ISSUE THREAD

**Issue by phr0gger** [vpelletier/python-libusb1#53]
pip install finishes claiming success
but import fails
Do I really have to use some package manager?
```
➜  ~ python3 -m pip install libusb1 
Defaulting to user installation because normal site-packages is not writeable
Collecting libusb1
  Downloading libusb1-1.8.tar.gz (78 kB)
     |████████████████████████████████| 78 kB 1.7 MB/s 
Building wheels for collected packages: libusb1
  Building wheel for libusb1 (setup.py) ... done
  Created wheel for libusb1: filename=libusb1-1.8-py3-none-any.whl size=59991 sha256=8cd2f4578571cbc04d273ed0d4218e1298a50494f579a146b0f20f00983b7ee6
  Stored in directory: /Users/Martin/Library/Caches/pip/wheels/e0/c8/71/5aad28fb4e963a6ff65d532fc58c1a2f018559bbe9e2655e07
Successfully built libusb1
Installing collected packages: libusb1
Successfully installed libusb1-1.8
➜  ~ python3                         
Python 3.7.3 (default, Mar  6 2020, 22:34:30) 
[Clang 11.0.3 (clang-1103.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import usb1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Martin/Library/Python/3.7/lib/python/site-packages/usb1/__init__.py", line 61, in <module>
    from . import libusb1
  File "/Users/Martin/Library/Python/3.7/lib/python/site-packages/usb1/libusb1.py", line 192, in <module>
    libusb = _loadLibrary()
  File "/Users/Martin/Library/Python/3.7/lib/python/site-packages/usb1/libusb1.py", line 166, in _loadLibrary
    return dll_loader('libusb-1.0' + suffix, **loader_kw)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(libusb-1.0.dylib, 6): image not found
>>> 
```

Inside Thonny the error message has the additional line:
`Did find: file system relative paths not allowed in hardened programs`

**Comment by vpelletier** [comment]
This means `python-libusb1` is failing to load the [`libusb` 1.x C library](https://libusb.info/) (called `libusb-1.0.dylib` on OSX). It is not part of `python-libusb1`, cannot be declared to `pip` as a dependency (because it is not a python package), and so has to be separately installed.

Is it installed ?

Is it in the [library lookup path](https://developer.apple.com/library/archive/documentation/DeveloperTools/Conceptual/DynamicLibraries/100-Articles/UsingDynamicLibraries.html) ? python-libusb1 is also extending the lookup path to a few unofficial OSX package managers: `/opt/local/lib/libusb-1.0.dylib` from macports and `/sw/lib/libusb-1.0.dylib` from fink.

**Comment by vpelletier** [comment]
> `file system relative paths not allowed in hardened programs`

This seems to be some (sandboxing ?) system from OSX, with which I am not familiar, and google does not bring anything which seem immediately relevant, so I'm afraid I won't be able to help much on this part. I have no experience with Thonny either, so I am not sure why it would cause such error and not a bare python interpreter.

**Comment by phr0gger** [comment]
Installed libusb with homebrew and all is well!
