### ISSUE TITLE
Send control request with invalid bmRequestType

### ISSUE THREAD

**Issue by FFY00** [vpelletier/python-libusb1#56]
Hi, I need to send a control request with a invalid direction in bmRequestType.

The device I want to talk to is awful and requires me to send some requests with the device to host direction, how can I do this?

Since `controlWrite` sets the direction bit, I tried to use `_controlTransfer` directly, but I run into the following error.

```
Traceback (most recent call last):
  File "./MD800E.py", line 140, in <module>
    main()
  File "./MD800E.py", line 95, in main
    dev.request(_Request.REG_READ, 0x0000, 0x0000)
  File "./MD800E.py", line 65, in request
    self._dev._controlTransfer(
  File "/usr/lib/python3.8/site-packages/usb1/__init__.py", line 1466, in _controlTransfer
    mayRaiseUSBError(result)
  File "/usr/lib/python3.8/site-packages/usb1/__init__.py", line 133, in mayRaiseUSBError
    __raiseUSBError(value)
  File "/usr/lib/python3.8/site-packages/usb1/__init__.py", line 125, in raiseUSBError
    raise __STATUS_TO_EXCEPTION_DICT.get(value, __USBError)(value)
usb1.USBErrorIO: LIBUSB_ERROR_IO [-1]
```

Please find attached a capture of what my packets need to look like. Sorry for the zip, Github won't let me upload the capture directly.

[md800e-512-384.zip](https://github.com/vpelletier/python-libusb1/files/5022921/md800e-512-384.zip)

**Comment by FFY00** [comment]
I managed to get it to work with `_controlTransfer`. Perhaps `controlWrite` could get a `direction` kw argument?

**Comment by vpelletier** [comment]
Hello,

Isn't `controlRead` what you need ? There are 2 differences between `controlRead` and `controlWrite`:
- the direction flag in the `bmRequestType` field of the setup stage. This I have control on as you saw in the code, and it conditions the next point.
- whether the provided buffer will be read from or written to, which depends on data stage direction. This is not something I have control on at this level (I believe even the kernel may not be able to cause an inconsistent data stage direction, as I think this is offloaded to the HCI - but I'm definitely not an HCI wizard, so do not quote me on this)

From what I understand from the capture, the setup transaction only has an `IN` data stage (device-to-host, which would be consistent with the `bmRequestType` flag), so it seems consistent. Or I'm missing something.

USB can be confusing at times, because at each protocol layer the directions can change.

**Comment by FFY00** [comment]
Yes! My bad :blush:
