### ISSUE TITLE
Check the version and the absolute path of the linked libusb library

### ISSUE THREAD

**Issue by hdemontis** [vpelletier/python-libusb1#67]
Hi,

I need a confirmation : we can choose the path of the `libusb-1.0-0.so.0` by manually setting the LIBUSB_BINARY before running `pip install libusb1`. Is that correct ? (for example if we work with the official source code)

Afterwhat, how can I see if it's working inside my code ? Any existing function or argument which return the path of the shared library ?

Thanks by advance.

**Comment by vpelletier** [comment]
Hello,

The intent of this environment variable is to embed a specific pre-built libusb library for distribution. This path is expected to point to a place `setup.py` extracts the latest libusb binary distributions (which is only for Windows at the moment), so that the library matching the wheel target OS gets distributed along with `python-libusb1`. It was not implemented with the expectation that it would be used/useful otherwise, but rather as an internal detail of the `python-libusb1` release process.

If you already have libusb installed and rather than distribute it you intend to make `python-libusb1` load this specific library, it should be possible to do by adding its location to the OS linker's configuration before importing `usb1.libusb1` (which also means before importing `usb1`). The exact way to configure the linker depends on the OS, on GNU/Linux it would be `LD_LIBRARY_PATH`, on OSX I believe it is `DYLD_LIBRARY_PATH`, and apparently on Windows it is `PATH`.

If you are releasing a version of `python-libusb1` itself, then maybe `setup.py` needs to be improved further. Which I'm not sure yet how I feel about, as it is already a bit too complex for comfort... But it will all depend on the patch.

If you are releasing another package which happens to depend on `python-libusb1`, then I feel you should rather handle this as part of that package's build process, and then setup the environment in python code to point to wherever the library ends up before importing `usb1`.

Going further: I'm nowadays not satisfied by how `usb1.libusb1` loads the library on module import, without a possibility for the user to control this in a more pythonic way than tweaking OS linker configuration (see also #37 ). Changing this will likely break the compatibility with any program out there which would be importing `usb1.libusb1` directly and never use `usb1`, as some extra step will be needed to load the library before anything in `usb1.libusb1` becomes usable. So I have not yet brought myself to do this, but maybe this would be what you need ?

**Comment by hdemontis** [comment]
Hi,
Thanks for replying. I am not expert enough on these kind of library import issues, so I don't think I am helpful in solving your problem. I will try to parse the `LD_LIBRARY_PATH` environment variable, and maybe override the `setuptools.command.install` to automate the OS linker.

**Comment by mcuee** [comment]
Interestingly pyusb has lots of issues complaining "no backend available".
Ref: https://github.com/pyusb/pyusb/issues/120

This is especially true under Windows because libusb-1.0.dll is not installed when people use Zadig to install WinUSB/libusbk driver, only libusb-0.1.dll (as well as libusbk.dll) is installed.

**Comment by mcuee** [comment]
Right now if people uses "pip install", libusb-1.0.dll (right now 1.0.24 release) is bundled. So I think this should sort out majority of the issues under Windows.

**Comment by mcuee** [comment]
On the other hand, if people use "python setup.py install" from git head, libusb-1.0.dll is not installed. So probably this needs to be documented somewhere. Usually I put libusb-1.0.dll in the same directory as Python.exe for my Windows Python virtual environment (typically venv/Scripts directory) and that works well with pyusb but it does not seem to work with python-libusb1.

**Comment by vpelletier** [comment]
> On the other hand, if people use "python setup.py install" from git head, libusb-1.0.dll is not installed. So probably this needs to be documented somewhere.

For background, my intentions here are:
- install from repository: user is responsible for having the library installed in whatever way makes sense for the environment (linux distro package, fink/homebrew/macports/... on osx, etc)
- install frop pypi when under windows: because there is (as reported) no neat way to tell the user how to install libusb, bundle it in specially-made wheels

Unfortunately, building the wheels expects a lot more from the environment than plain install (especially gnupg with a pre-established trust keyring able to validate the archive signature, and then 7z to extract the correct dll), not to mention the reliance on how the libusb.info html page looks like. In my uploader role, I am ready to tweak this every few libusb release, and setup.py only needs to contain whatever works at the time I'm releasing. But I do not think I can reasonbly expect the same from anyone installing from repository. This is why the dll download & extraction codepath is tucked away where only my release shell script can trigger it.

Independently from my intentions, I agree that it should be documented, and I added it in 8cc99d613b5bfd805b887803cc65eb9f16702389 .

> Usually I put libusb-1.0.dll in the same directory as Python.exe for my Windows Python virtual environment (typically venv/Scripts directory) and that works well with pyusb but it does not seem to work with python-libusb1.

I did this, but without a venv, to test from git, and for me it worked.

More precisely, I:
- installed from pypi, to get the correct libusb dll version
- copied that dll to `C:\Users\$USER\AppData\Local\Programs\Python\Python39`
- installed from a working copy (with `Scripts/pip.exe install $PATH_TO_REPO` rather than invoking setup.py myself, but it should not change the result)

**Comment by mcuee** [comment]
Here is what I do without using virtual environment.

```
C:\Users\xfchen>path=C:\Python39;C:\Python39\Scripts;$PATH

C:\Users\xfchen>pip install libusb1
Collecting libusb1
  Using cached libusb1-1.9.3-py3-none-win_amd64.whl (137 kB)
Installing collected packages: libusb1
Successfully installed libusb1-1.9.3

C:\Users\xfchen>cd c:\work\libusb\python-libusb1\examples
c:\work\libusb\python-libusb1\examples>python listdevs.py
ID 0424:5744 Bus 003->4->3->2 Device 5
ID 0bda:5413 Bus 003->2->3 Device 6
ID 0bda:0413 Bus 003->4->3 Device 3
ID 0424:2740 Bus 003->2->3->2->5 Device 14
ID 413c:b06e Bus 003->2->5 Device 7
ID 046d:c534 Bus 001->1 Device 1
ID 8087:0aaa Bus 001->14 Device 4
ID 0424:2744 Bus 003->2->3->2 Device 8
ID 0bda:5487 Bus 003->2 Device 2
ID 0bda:0487 Bus 003->4 Device 1
ID 047f:c056 Bus 003->2->3->2->2 Device 11
ID 0bda:402e Bus 003->2->3->4 Device 9
ID 8086:a36d Bus 001 Device 0
ID 413c:2107 Bus 003->2->3->2->3 Device 12
ID 0a5c:5842 Bus 001->10 Device 2
ID 8086:15f0 Bus 003 Device 0
ID 8086:15db Bus 002 Device 0
ID 0bda:8153 Bus 003->4->4 Device 4
ID 413c:b06f Bus 003->2->3->5 Device 10
ID 046d:c077 Bus 003->2->3->2->4 Device 13
ID 0bda:58fd Bus 001->11 Device 3
```

Remove libusb-1.0.dll to C:\Python39 to be the same directory of libusb-1.0.dll, that is okay, just as what you have done.
```
c:\work\libusb\python-libusb1\examples>python listdevs.py
ID 0424:5744 Bus 003->4->3->2 Device 5
ID 0bda:5413 Bus 003->2->3 Device 6
ID 0bda:0413 Bus 003->4->3 Device 3
ID 0424:2740 Bus 003->2->3->2->5 Device 14
ID 413c:b06e Bus 003->2->5 Device 7
ID 046d:c534 Bus 001->1 Device 1
ID 8087:0aaa Bus 001->14 Device 4
ID 0424:2744 Bus 003->2->3->2 Device 8
ID 0bda:5487 Bus 003->2 Device 2
ID 0bda:0487 Bus 003->4 Device 1
ID 047f:c056 Bus 003->2->3->2->2 Device 11
ID 0bda:402e Bus 003->2->3->4 Device 9
ID 8086:a36d Bus 001 Device 0
ID 413c:2107 Bus 003->2->3->2->3 Device 12
ID 0a5c:5842 Bus 001->10 Device 2
ID 8086:15f0 Bus 003 Device 0
ID 8086:15db Bus 002 Device 0
ID 0bda:8153 Bus 003->4->4 Device 4
ID 413c:b06f Bus 003->2->3->5 Device 10
ID 046d:c077 Bus 003->2->3->2->4 Device 13
ID 0bda:58fd Bus 001->11 Device 3
```

However, moving libusb-1.0.dll to the C:\Python39\Scripts, it will fail even though it is in the path.
```
c:\work\libusb\python-libusb1\examples>python listdevs.py
Traceback (most recent call last):
  File "c:\work\libusb\python-libusb1\examples\listdevs.py", line 18, in <module>
    import usb1
  File "C:\Python39\lib\site-packages\usb1\__init__.py", line 61, in <module>
    from . import libusb1
  File "C:\Python39\lib\site-packages\usb1\libusb1.py", line 185, in <module>
    libusb = _loadLibrary()
  File "C:\Python39\lib\site-packages\usb1\libusb1.py", line 157, in _loadLibrary
    return dll_loader(filename, use_errno=True, use_last_error=True)
  File "C:\Python39\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'libusb-1.0.dll' (or one of its dependencies). Try using the full path with constructor syntax.

c:\work\libusb\python-libusb1\examples>path
PATH=C:\Python39;C:\Python39\Scripts;$PATH

```

**Comment by mcuee** [comment]
https://github.com/vpelletier/python-libusb1/commit/8cc99d613b5bfd805b887803cc65eb9f16702389
I think the above document fix is good enough. However, it is a bit strange that libusb-1.0.dll in the Path is not searched.

**Comment by mcuee** [comment]
```
(py39venv) C:\work\libusb\python-libusb1 [master ≡ +1 ~0 -0 !]> $Env:PATH
C:\work\python\py39venv\Scripts;..

(py39venv) C:\work\libusb\python-libusb1 [master ≡ +1 ~0 -0 !]> which python

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     python.exe                                         3.9.4150.… C:\work\python\py39venv\Scripts\python.e…

(py39venv) C:\work\libusb\python-libusb1 [master ≡ +1 ~0 -0 !]> which pip

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     pip.exe                                            0.0.0.0    C:\work\python\py39venv\Scripts\pip.exe


(py39venv) C:\work\libusb\python-libusb1 [master ≡ +1 ~0 -0 !]> which libusb-1.0.dll

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     libusb-1.0.dll                                     1.0.24.11… C:\work\python\py39venv\Scripts\libusb-1.0.dll

(py39venv) C:\work\libusb\python-libusb1 [master ≡ +1 ~0 -0 !]> python .\examples\listdevs.py
Traceback (most recent call last):
  File "C:\work\libusb\python-libusb1\examples\listdevs.py", line 18, in <module>
    import usb1
  File "C:\work\python\py39venv\lib\site-packages\usb1\__init__.py", line 61, in <module>
    from . import libusb1
  File "C:\work\python\py39venv\lib\site-packages\usb1\libusb1.py", line 185, in <module>
    libusb = _loadLibrary()
  File "C:\work\python\py39venv\lib\site-packages\usb1\libusb1.py", line 157, in _loadLibrary
    return dll_loader(filename, use_errno=True, use_last_error=True)
  File "C:\Python39\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'libusb-1.0.dll' (or one of its dependencies). Try using the full path with constructor syntax.

```

**Comment by vpelletier** [comment]
Oh, Windows uses `PATH` also for libraries ? Indeed, then it is surprising it could not locate it. I only knew that it would look up in the same directory as the executable doing the lookup. Could python's `PATH` be different from its parent shell ? I'm thinking of something like unix shell `export`, but I have no idea if this exists in Windows.

**Comment by mcuee** [comment]
Yes, by right PATH is used for libraries.

https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order#standard-search-order-for-desktop-applications

If SafeDllSearchMode is enabled, the search order is as follows:
1. The directory from which the application loaded.
2. The system directory. Use the GetSystemDirectory function to get the path of this directory.
3. The 16-bit system directory. There is no function that obtains the path of this directory, but it is searched.
4. The Windows directory. Use the GetWindowsDirectory function to get the path of this directory.
5. The current directory.
6. The directories that are listed in the PATH environment variable. Note that this does not include the per-application path specified by the App Paths registry key. The App Paths key is not used when computing the DLL search path.

**Comment by mcuee** [comment]
In the case of virtual environment, Windows Python adds "venv\Scripts" to the PATH. The "Scripts" folder has python.exe and pip.exe in the same directory. So it is very strange that python-libusb1 can not find libusb-1.0.dll in the Scripts folder.

**Comment by mcuee** [comment]
BTW, I am not so sure if you want to support alternative names of libusb-1.0.dll under Cygwin, which is cygusb-1.0.dll. And if you want to support FreeBSD (which has its own libusb-1.0 implementation outside libusb project), then you may want to use some tricks like the following.

https://github.com/pyusb/pyusb/blob/67550ed625e4252c0d586dd8ed5de681f4ad4edc/usb/backend/libusb1.py#L276

**Comment by vpelletier** [comment]
> cygusb-1.0.dll

It looks like there is some magic going on, as I can apparently import in ctypes it as `libusb-1.0.so`, even though I do not have such a file anywhere (...that windows file search can reach, anyway...). I do find `cygusb-1.0.dll` in cygwin's `/usr/bin` though. And cygwin's `which` appears to agree:

```
$ which libusb-1.0.so
which: no libusb-1.0.so in (/usr/local/bin:/usr/bin:/cygdrive/c/Windows/System32:/cygdrive/c/Windows:/cygdrive/c/Windows/System32/wbem:/cygdrive/c/Windows/System32/WindowsPowerShell/v1.0:/cygdrive/c/Windows/System32/OpenSSH:/cygdrive/c/Program Files (x86)/GnuPG/bin:/cygdrive/c/Program Files/Calibre2:/cygdrive/c/Users/vincent/AppData/Local/Microsoft/WindowsApps
$ which cygusb-1.0.dll
/usr/bin/cygusb-1.0.dll
```

Unless I have somehow tainted my cygwin install (I believe I did it a while ago, I could have forgotten).

**Comment by vpelletier** [comment]
I'm closing this issue as I believe the documentation fix should be enough. Feel free to reopen if there are more elements to document, like if the above Windows behaviour (not following PATH) gets understood.

**Comment by mcuee** [comment]
Yes, I am okay with the current documentation fix.

**Comment by mcuee** [comment]
BTW, it seems to me that there is also no need to have the trick under FreeBSD, under FreeBSD, it magically uses libusb.so.3 and not libusb-1.0.so which does not exist under FreeBSD. But I can not test FreeBSD now since I somehow can not get usb to work as of now with Virtual Box under Linux (x86_64).
